### ISSUE TITLE
Sometimes color chosen matches terminal background

### ISSUE THREAD

**Issue by kyldvs** [glennsl/timber#3]
I've noticed that sometimes a color is picked that matches the background of my terminal, can we automatically avoid this somehow? Perhaps by avoiding dark colors?

<img width="979" alt="Screen Shot 2020-02-28 at 4 48 29 PM" src="https://user-images.githubusercontent.com/1830497/75597449-5d712f80-5a4a-11ea-82db-c8ca836b67ab.png">

The full contents of the screenshot:

```
[INFO]   +201ms AAA.WindowManager : Creating window
[DEBUG]  +415ms AAA.FileSystem : Writing: /Users/kad/Library/Application Support/Ads Template Manager - Demo/.metadata
```

**Comment by glennsl** [comment]
Hm, I've never encountered this myself. We do avoid pure black and pure white:

https://github.com/glennsl/timber/blob/2e06a70f85e504470ad0b740ae1bc36ad660a5d6/src/Namespace.re#L2-L19

And we can disable others as well, but I'm wondering if this might not just be because of the custom colors you've configured. Perhaps you have `` `Hi(`Black)`` set to black instead of gray, for example?

**Comment by kyldvs** [comment]
Interesting, that's possible, I'll confirm which color codes are actually printing

**Comment by kyldvs** [comment]
It looks like Dark Gray is the color code causing problems, specifically `\e[90m`: 

https://gist.github.com/kyldvs/42cb7d9a1e0da81228599a0b9a85d7d9

Is it fine to remove this color code too? Even if it were to show up correctly I suspect it is not a very user-friendly color due to the very low contrast with the background when rendered correctly: 

![image](https://user-images.githubusercontent.com/1830497/75814914-67937680-5d47-11ea-8309-054bb9db77ad.png)

**Comment by glennsl** [comment]
`` `Hi(`Black))`` shouldn't be dark gray, but around 50% gray, which is very much legible. And if that's where we draw the line we ought to cut most non-hi colors as well. See https://en.wikipedia.org/wiki/ANSI_escape_code#3/4_bit

This still seems like an issue specific to the theme you're using. Most terminal emulators make ti easy to tweak single colors if you need to as well, so I'm afraid I still don't see the need to make this a library-level fix.

**Comment by kyldvs** [comment]
When looking through screenshots online of different color schemes "\`Hi(\`Black)" is consistently one of the lowest contrast colors on a dark background (whether that is the "correct" color or not). I believe keeping it in hurts the default accessibility of this library. I'd still like to see this fixed. I do not understand why it is particularly important to have this color in the rotation.

That said, my specific issue of it being invisible is a problem with defaults in my terminal and I can resolve it on my own: https://github.com/alacritty/alacritty/issues/3404

**Comment by kyldvs** [comment]
Feel free to close BTW if you don't want to remove the color. That's totally fine even if I might disagree :)

**Comment by glennsl** [comment]
I'm not completely against removing it, but when you only have 14 colors available, removing just one color is 7% of the color space, which is pretty significant when the purpose of the colors are more to make identifiers distinguishable at a glance than easily readable. And I also don't see that the standard red, green and blue colors are all the much more legible, so why should they remain if this is removed? So at the very least I'd like to see more than just anecdotal evidence.

Closing this for the moment then, but am still open to reconsider given good evidence.
